# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 606c47d15281c5ccc242a5f417f439506dd9d508ba9b7c194d2a5c3308852ac881390570e2b11506aa9b5f14e623697fffe5602bf0c1cdbdfb39344a7d49c5fd

test:
  secret_key_base: 12c62fad0aa8cbe0c09eb96a02557eaa39a20521740157e719034bcffecbe916309e76130c03d728b685cdc0abb6b387fdc6e03f68f29640fdb604d849506cb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
